from turtle import Screen, Turtle

screen = Screen()
screen.title('Girl with a Pearl Earring')

size = 9.2
c_size = 20

Palette = {
     'A': '#06050a',
     'a': '#0d0d0d',
     'B': '#1f1f1f',
     'C': '#3c3b49',
     'D': '#201d16',
     'd': '#14120e',
     'E': '#4b3b2c',
     'e': '#67727a',
     '&': '#525b61',
     '^': '#3c4347',
     'F': '#6b4f41',
     'f': '#945332',
     '*': '#734127',
     'G': '#3a2721',
	 'H': '#8d8053',
	 'I': '#7f6535',
	 'J': '#b69069',
	 'K': '#6e5b3b',
	 'L': '#917357',
	 'M': '#ccc599',
	 'N': '#9c7f3d',
	 'O': '#b79041',
	 'P': '#6c708b',
	 'Q': '#93989e',
     'q': '#858585',
	 'R': '#8e97c0',
     'r': '#b4bad5',
	 'S': '#5e6fa7',
     's': '#7786b5',
	 'T': '#3c4166',
     't': '#4b517f',
	 'U': '#111739',
     'u': '#161d48',
	 'V': '#eed2ba',
	 'W': '#e3dfd4',
     'X': '#373737',

}

Art = [
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADDDDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADEEEEEEFEEEEEGDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEMMMHIHJHIIIIKEDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHMMMIIMLLMMMMMMJIEEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADGMMMIMMKLMMVVVVMMJKEDDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABKHHHHHLKKHMMVVVVVMMHKKEDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGKHHJJMMMJMMMJNNOMVVVMMHIKKEDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADFFHMMMOMVVMMJMMMMNMMMMJJNIEKKEDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABDDHMMMMMMOMVVVMLIJJMMHIKJJJJIFGEKEDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADCCPPPQQQQQQQQQHMMVVMIHJMMHKKIJJHKEEEEDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAADDCPPRRPRPPPPsPCCPTMVVVMLHJMMHLLNJJLEDDDEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAABCPQRRRRPPRRRRRRRssSSTTTPVVMIHJMMLLLKINHEEDDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAADCPRRrrrrRRRRRRRRsSSSStTTTQQMMHJHMLLLLKIHHEEDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAABCPPPRRrrrRRRRRRssssssStTTTSSFMMIHLMLLHLEIIHEEDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAADCRRRRRrrrrrRRRRssssssssSStTTTTTMMHHHLFKKLFEEHDDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAADCPRRrrrrrrrrRRRssssssssssStTTTTTTMMHHJFFFLEEEEDDDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAADERRRrrrrrrrrRRRRRsssssssssSStttTTTTPMHIJEEEEEHKDDDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAABCPPRrrrrrrrrRRRRRsssssssssssSSStTTTTCCLLKJEDDEHEDDDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAACPRRRrrrrrrrrRRRRssssssssssSSsSStTTTTUBCFKKEEDGHEGDDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAPRrrrrrrrrrrrRRRssssssSSSSSsSSStSttTTTTUBDFKFGDKJEDDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAACPRRrrrrrrrrrrrrRRsssssSStSSSttSSSSSttTTTTUBGEFEEIMKDDDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAACPPrrrrrRRRRrrrrRssssssssStSSSStSStTTTtTTTTTBDEEEHMIDDDGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAABCPrrrrRRRPPRRrrRssSSSSssssSSSSSSSStTuTTTTTuuUUEEFMMJDDDEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAABCRRRRPRRRRRPRRRRsSSSttSSssSSSttttStUUuuTTuuuuUBGEMMMJDDEGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAABPPSPPPPRPRRRRRRRsSttTTttSSsSttTTTttUUauTTuUuuuUBEMMMJDDEGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAPPTQQQQQQRRRPPPPPttSTTTTTtSSStTuuuTTUUaauuUUUuuUBGMMMJDDEEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAACPQQVVVVVQQPPPPSttTTTTTTTTtStTaaauuuuuuuUUUUBuuUBBJMMJDDFEDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAABFMVVVVVVVVQPSSSStttttTTTTTttTTaUaUuuuuuuuuBBUuuUBHMMJDDKFEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAADJVVVVVVVVVVVMJPPSSttRSTTTTTTTTTTUUUuuuuuuuuUUUUuuUEIMGDDEEEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAADJVVVVVVVVVVVMMJQPPtTRRTUTTTTTTuuuUUuuuuuuuuUUUUuuBEIMGDDEEEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAADJVVVVVVVVVVVVMMJJCCTSRuaUTTuuuuuUUuuuuuuuuUUBUUUuBDKMEGDEEEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAEFVVVVVVVVVVVVVVMMJLFCTTTuaaUUUUUUUUuuuuuuuuuUBBUUUBAKMGGDGEEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAFLVVVVVVVVVVVVVVMMMJLFCCTuuaaaaaUUUUUuuuuuuuUUBBUUUaaKMGGDDEEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAALMMMVVVVVVVVVVVVMMMMJJKFBuuuBBaaaUUUaauuuuuuuUUUUUUUAKMGDDDEKDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAFMMMMVVVVVVMMMMMMMMMMJLFECBuuuaaUUUUUBBaaaaauuuuUUUUBLMEGDDEKDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAEJMMMMVVVVMJJJJJJMMMMJLLFGCBuuuUBUUUUUUBBBaaauuuuUUaBLMEGDDEKDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAADGFLLJMVMMLLLLLJJJJJJJJLFEGABBuuuUUUUUUUaaBaauuuuUUaaKMEEGDEHEDAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAADGMWFFLVMJLLLLJJJJJJJJJLFEGdBBBBuuuuUUUUUaaaBUuuuUaaaKMKEGDEKEDBAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAADEW&AGFVMJLLLLJMMMMJJJLLFEGGddBBuuuuUUUUUUaaUUuuuUUaaKMKEGDEKEGBAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAEJV^^&LVJLKLLLMHHHFFFKKKEGGGGddBBuuuuUUUUUUaUUUuuUUBaKMKEEDEKKEBAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAFMJLLLVVJLKLJJJVVWEEEEFFEGGGGGddBuuuuUUUUUUuuuUUuUUBAKMMEEDEKKEDAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAFMMMMMVVLLFLJJVVWDAeGEEEEEGGGGGdduuuuUBBaaUUuuuUUUUUAKMMEEDEKKKDAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAALVMMMVVMLLLLJMJVW^^&FEEEEEEEGGGGdBBuuuBBBaaUUuuUUUUBAEKMMKDEKKKDAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAALVVVVVVJLLLLJVMJJFFFFGFFFFFEGGGGDdBBuuuBBaaUUUUuUUBaAEKMMIDGEKEDBAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAALVVVVVMJLLFLJVVMMJLLLLJJJLLEGGGGDDDdBuuuuuaaaUBBUBaAADEMMHEDDEGDBBAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAADLVVVVVJLLFFLJVVVVMMMMMMJLLFEGGGGGDDDBBBuuuuBaaUaaaaAADEMJHEDDEEDBBAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAADLVVVVMJLFFFLJVVVVVVVVVMJLLFEGGGGGGDDDduuuuuuBaaaaaBAADDMJHEDDKKDCCAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAABLVVVVJLLFFFLJVVVVVVVVVMJLFFGGGGGGGGDDDBBBuuuBaaaaaAADDDMJMEGDKKDBCBAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAALVVVVLLLFFFLJVVVVVVVVMJLLFEGGGGGGGGGDDDDBuuuBaaaaAAADDDMJMEGDHHDBBBAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAALVVVJLFFFEEFJMVVVVVVMJLLKFEGGGGGGGGGDDdddBBuBaBAAAAAADDMJMEGDMHDDBBBAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAALVVMJFFFFEEEFMVVVVVMJJLLFEGGGGGGGGGDDdddDDBBBBAAAAAAAADMJMEGDHMDDBBBAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAALVVMLFEEEEEGFMVVVVVMJJLFFEGGGGGGGGGGddDDGDABBAAAAAAAAADMHMEEDHMDDBCBAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAEMVVVLFGGGGGFMVVVVVMJLLFFEGGGEGGGGGGGDDGDDAAAAAAAAAAAADMHMKEGHMEDDCBAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAELVVVJLEEEEFFMVVVVVMLLFFFGGGGEEGGGGGGDGEDDAAAAAAAAAAAADMHMKEGMMHEDCBBAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAADFVVVVJLFFFLMMVVVVMJLLKFEGGGGEEGGGGGGEEGDAAAAAAAAAAAADDMHMKEGMMMKDBCCAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAADVVMVJLLLLJMMVVVMJLLKFFEEGGEEEGGGGEDEGDAAAAAAAAAAAAADDMJMIKGJVMKDCCPBAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAADVMJJMLLLLLJMMMMJJLLKFFEEEGEEEGGGGDEEDAAAAAAAAAAAAAADDMJJMKGMVMKDCCPBAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAADMMFffFLLLLLJMJLLLLLFFEEEEEEEGGGGGDDDDAAAAAAAAAAAAAADDMMJMMGMVVKDBCCPCAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAEMJFLJfffFFLMJJLLKFFEEEEEEEEEEGGGDXXDDAAAAAAAAAAAAAADMMJMMEHMVKDBCCCBBAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAADMLffFJLEEfFMMJLLFFFFEEEEFEEEEEGGXXXDAAAAAAAAAAAAAAADMMJHMEHMMKEBCCCBBAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAADJJMMffff*FJMMJLLFFFFFEEEFFFEEEGqXXXXaAAAAAAAAAAAAAADMMJHMEKHMHKABCPCBAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAADFMLL****FFLJJJLLFFFFFFEEFFFFEEGWqXXaaAAAAAAAAAAAAAADMMJJMKKKMMHBBCPCBAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAEJMMJLLLLJJJJLLFFFFFFFFFFFFFEEGXWXaaaAAAAAAAAAAAAAADMMJJMKEKMMMBBCCCCBAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAADEVVVMMMLLKLLLLFFFFFFFFKKFFEEDGBXXaaqAAAAAAAAAAAADADMMJHMJKKMVMDBBCCPBBAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAVVVVVVMLKLLLKKFFFFFFKLLFEEEGGGXqqqADAAADDGGCCDDDDDMMHHMJKKMVMDBBCCPCBBAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAVVVVVVMLKKKKKKKFFKKKLLFEGEGGGGGEFFEDAAACCFFFEEEDDDMMJMMMKKMVMDBBBCPPCBAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAKVVVVVMJLFFFKKKKKKLLLLEEEGGGGGGGGGECPPPQQQQLFEEEDDMMMMMMKKMVMDBBCBCPCBAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAEKMMMMMJLFFFFKKKLLLLFEEEEGGGGEEFFFQQQQQQQQQLLEEGDDMMMMMMKKMVMDBBCBBPCBBAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAADELLJJJLFFFFFEEEEGGEEEEEEEEEGELQWWWWWWWQQQQQQFFDDDJMMMMMKKJMMDDBCCBCPCBAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAADDGGGGGDDDDDFFFFFEFFEFFLWWWWWWWWWWWQQEEEEEEGDDDDJJMMMMHHHMMDDDCCCBCPBBAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFLLKKFFFFFLWWWWWWWWWQQQQFDDDDDDDDDDDHJMJMJHMKMMGDDBCCBCPBBAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADFJJJLLQWWWWWWWWWWWQFEDDDDDDDDDDDDDdEHMJMJHMEJMFDABCCCCPCBAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADELJMMVWWWWWWWQQQFFEEDDDDDDDDDDDDDdADHMJJHHMEHMMFABBCCCPCCBAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADFJVWWWWWWWWWFEEGEEDDDDDDDDDDDDDddAAKMJJHHMEHMMKDBBCCCCPBBAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGVWWWWWWWMLKEEEEDDDDDDDDDDDDdddddADKMJHMHMEHMMLDDBBPCBPPBBAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGLWWWWWWMMJLKEEGDDDDDDDDDDDDdddddAAAKMHHMHMEHJMKDDBBPCCPPUBAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFWWWWWWVJILLKFEGGDDDDDDDDDDddddddAAAEMHHMHMMLHMKDABBPCCPPUBAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADWWWWWWJNNNNNIKFEEDDDDDDddddDDddddAAAAEJMHMHMMHKMFDAABPCCPQPCBAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGFWWWVMVJNOOONIKFEDDDDDDDdddddddddAAAAAEHMJMHMMKKMFDAABPPCCPQCCBAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQWWWWLIOOOOOONNIFEDDDDDDdddddddddAAAAAAEHMJMHHMKEHFDDDBPPCCCQPCBAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADQWWVLNNOOOOONIIKEEDDDDDDdddddddddAAAAAAEHMJMHHMKEFEDDBBPBBCCQMPBBAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEQWWMINNOOOOONIKFEEDDDDDDDDddddddddAAAAAEHMJMHHMKEFFCBBBPPBBCQMPCBAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQQWKINOOOOOOOOIKEEGDDDDDDDDDdddddddAAAAAEKMMMMHMKFqqPCCBPPPBBPQMPBAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQQHLHNOOOOOOONKKEEEGDDDDDDDDddddddddAAAAEKMMMJJMKFqQCCCCCPQPPQMMQCBAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQLIHHNOOOOOOONIKFEEGDDDDDDDDDdddddddAAAAEKJMMJJJKFqPPCCCCPQMQMMMQCBAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHHIIINOOOOOOONNHHEEDDDDDDDDDDddddddAAAAAEKMMMJJJKEqQQCBCCPPQMMMMQPBBAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAADDINNINNOOOOOONNNNIEEDDDDDDDDDddddddAAAAAAEKMMMJJJKFqQQCBBCPQMMPMMQQPBAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAADEINNNNOOOOOOONNNNIEEDDDDDDDDddddddAAAAAAAELMMMHHHKFqQQCCBCPQMMPMMMQQBAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAADEKNNOINOOONIIINNNNIKFDDDDDDddddddddAAAAAAADEMHLqqqqPTPQPPCBCQMMMQMMQPBAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAADEKNNONNONNIIINNNNNNHKFDDDDdddddddddAAAAAAADGLLqQQMQPCPPQPCBCQMMMQMMPPBAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAADEKNOONNNIIIINNNNINNNIKDDDDdddddddddAAAAAAABBFPqQMMQPCPMQQCBCQQMMQMMPtBAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAKKKHIIKKKIIINOOOOOOOONIEDDDDdddddddddAAAAAABCqqQQMMQPCPQQQCCCCQMMQQQPtBAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAADKKKHIKKKKIIINOOOOOOOONIEDDDDDDDddddddAAAAAABCQQQPQMQPBCQQCCBCCPQMQQPttBAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAADEKKKHKKKKKHHNOOOOOOOONNIEDDDDGGGDddddddAAAAABCQQPPQMQQBBCBBBBBCQQQPPAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAEFKKKKKFLLHNNNNNNNNNNNNNIEDDDDGGGGDddddddAAAABCPPPPQQQQBBBAAAAAAADDDDAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAEKLLLKKLLLHNNNNNNNNINNNNIEGDDDGGGGDDddddddAAABCPPttPQQQBBBAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAEFLLLKKLHHINNNNNNNIIINNIIEGDDDGGDGGDDDdddddAABCPtttPQQtCBBAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAEKKKKLLLNNNNNNNNNIIIIINIIKEDDDGDDDDDDDDddddAABCttPPPPttCBBAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAEKKKKLHHNNNNNNNNIIIIIIINIIKDDDDDDDDDDDDDdddAABCttPttttCCBAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAADEKLLLINNNNNONNIIKLLLLLLINIKEEGDDDDDDDDDDDdddABBCttCCCCCBAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAEKLLLNNNNNONNNIKKKKLLKKINIKEEEDDDDDDDDDDDdddABBBBBBBCBBBAAAAAAAAAAAAAAAAAAAAAAAAA",
]

WIDTH, HEIGHT = len(Art[0]), len(Art)
screen = Screen()
screen.setup(1000, 1000)
screen.tracer(False)

turtle = Turtle()
turtle.hideturtle()
turtle.shape('square')
turtle.shapesize(size / c_size)
turtle.penup()


x0 = -500
y0 = 500

for i, row in enumerate(Art):
    turtle.setposition(x0, y0 - i * size)

    for pixel in row:
        turtle.color(Palette[pixel])
        turtle.stamp()
        turtle.forward(size)

screen.exitonclick()

screen.tracer(True)

'''Credit to cdlane on stackoverflow.com for inspiring the method used to create this Art'''